// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjZA5qdkXGqXKgsH0-0Kl6OVLJRQ0vtjg',
    appId: '1:243421149371:web:0d65f5156891892cf0919e',
    messagingSenderId: '243421149371',
    projectId: 'musicapp-cccfd',
    authDomain: 'musicapp-cccfd.firebaseapp.com',
    storageBucket: 'musicapp-cccfd.appspot.com',
    measurementId: 'G-KTGS1F9EGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZ5616sCSRY_mcPzg0kFf1A-qJ1a1z2s',
    appId: '1:243421149371:android:98a027b6e5672c7bf0919e',
    messagingSenderId: '243421149371',
    projectId: 'musicapp-cccfd',
    storageBucket: 'musicapp-cccfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOlq6tpq6dhNsYKvZpWptkBbRzaqFaJA',
    appId: '1:243421149371:ios:6510f4703ca2724bf0919e',
    messagingSenderId: '243421149371',
    projectId: 'musicapp-cccfd',
    storageBucket: 'musicapp-cccfd.appspot.com',
    iosClientId: '243421149371-j5lejg6sm33lfjeq4jjkdogsh1ma8lko.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnOlq6tpq6dhNsYKvZpWptkBbRzaqFaJA',
    appId: '1:243421149371:ios:c1988d1f0ad6b21bf0919e',
    messagingSenderId: '243421149371',
    projectId: 'musicapp-cccfd',
    storageBucket: 'musicapp-cccfd.appspot.com',
    iosClientId: '243421149371-cn3ctsd59e3no5f85ba2cfhh1joio0te.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp.RunnerTests',
  );
}
